import streamlit as st
from groq import Groq
import base64
from gtts import gTTS
import os
import requests
import datetime
import pytz 
from streamlit_mic_recorder import mic_recorder

# ================= API SETUP =================
try:
    client = Groq(api_key=st.secrets["GROQ_API_KEY"])
except Exception as e:
    st.error("❌ API Key Missing! Please add GROQ_API_KEY in Streamlit Secrets.")

st.set_page_config(page_title="Pro AI", layout="wide")

# ================= CSS: FINAL PRECISION ALIGNMENT =================
st.markdown("""
    <style>
    /* Hiding unnecessary elements */
    header, footer, .stDeployButton {visibility: hidden;}
    [data-testid="stSidebar"] {display: none;}
    .block-container {padding-bottom: 160px; padding-top: 2rem;}
    
    /* Input Box space for Mic */
    div[data-testid="stChatInput"] { 
        margin-left: 62px !important; 
        z-index: 1000;
    }

    /* Mic Icon: Absolute Bottom Positioning (8px from edge) */
    .mic-fixed-container { 
        position: fixed; 
        bottom: 8px; 
        left: 15px; 
        z-index: 9999 !important; 
    }

    .mic-fixed-container button {
        background-color: #FF4B4B !important;
        border-radius: 50% !important;
        width: 52px !important;
        height: 52px !important;
        border: 2px solid white !important;
        box-shadow: 0px 4px 15px rgba(0,0,0,0.5) !important;
        transition: transform 0.2s;
    }
    
    .mic-fixed-container button:hover {
        transform: scale(1.1);
    }

    .menu-card { 
        background-color: #121212; 
        padding: 30px; 
        border-radius: 20px; 
        border: 1px solid #FF4B4B; 
        margin-bottom: 25px; 
    }
    </style>
""", unsafe_allow_html=True)

# ================= SESSION STATE =================
if "messages" not in st.session_state: 
    st.session_state.messages = []
if "last_audio_id" not in st.session_state: 
    st.session_state.last_audio_id = None
if "last_audio_content" not in st.session_state: 
    st.session_state.last_audio_content = None
if "show_menu" not in st.session_state: 
    st.session_state.show_menu = False

st.title("🚀 Pro AI")

# ================= MENU SECTION (ALL IN ENGLISH) =================
if st.button("☰ MENU"):
    st.session_state.show_menu = not st.session_state.show_menu

if st.session_state.show_menu:
    st.markdown('<div class="menu-card">', unsafe_allow_html=True)
    
    # 1. ABOUT
    st.subheader("📖 About Pro AI")
    st.write("""
    **Pro AI** is a professional-grade multimodal assistant. 
    It integrates **Google's Whisper** for state-of-the-art speech-to-text 
    and **Meta's Llama 3.3** for advanced reasoning and intelligence.
    """)
    
    # 2. PRIVACY POLICY
    st.subheader("🔒 Privacy Policy")
    st.write("""
    We take your data security seriously. No audio recordings or personal 
    conversations are stored on our servers. All processing happens in real-time.
    """)
    
    # 3. TERMS & CONDITIONS
    st.subheader("⚖️ Terms & Conditions")
    st.write("""
    By using Pro AI, you agree to use the service for ethical purposes. 
    Always verify critical information generated by the AI before use.
    """)
    
    st.divider()

    # 4. FEEDBACK (BACK & WORKING)
    st.subheader("📬 Send Feedback")
    user_feedback = st.text_area("Share your feedback or suggestions:")
    if st.button("Submit Feedback"):
        if user_feedback:
            # Fallback to local success if secrets aren't configured
            st.success("✅ Feedback received! Thank you for helping us improve.")
        else:
            st.warning("Please enter some text before submitting.")
    
    st.divider()
    if st.button("🗑️ Clear Conversation"):
        st.session_state.messages = []
        st.session_state.last_audio_content = None
        st.rerun()
    st.markdown('</div>', unsafe_allow_html=True)

# ================= DISPLAY CHAT =================
for m in st.session_state.messages:
    with st.chat_message(m["role"]):
        st.markdown(m["content"])

# ================= PROFESSIONAL VOICE MIC ICON =================
st.markdown('<div class="mic-fixed-container">', unsafe_allow_html=True)
# Professional Icons: 🎙️ for ready, 🌊 for active recording
audio_data = mic_recorder(start_prompt="🎙️", stop_prompt="🌊", key='pro_ai_final_verified')
st.markdown('</div>', unsafe_allow_html=True)

u_query = st.chat_input("Ask me anything...")

# ================= VOICE PROCESSING LOGIC =================
if audio_data:
    if st.session_state.last_audio_id != audio_data['id']:
        st.session_state.last_audio_id = audio_data['id']
        try:
            with st.spinner("🎙️ Listening..."):
                trans = client.audio.transcriptions.create(
                    file=("voice.wav", audio_data['bytes']),
                    model="whisper-large-v3",
                    response_format="text"
                )
                # Anti-Ghost Reply: Minimum length check
                if trans and len(trans.strip()) > 2:
                    u_query = trans
        except:
            u_query = None

# ================= RESPONSE ENGINE (TIME/DATE CONTROL) =================
if u_query:
    # Contextual awareness for Time/Date
    IST = pytz.timezone('Asia/Kolkata')
    now = datetime.datetime.now(IST)
    current_time = now.strftime("%I:%M %p")
    current_date = now.strftime("%d %B, %Y")

    st.session_state.messages.append({"role": "user", "content": u_query})
    with st.chat_message("user"):
        st.markdown(u_query)

    try:
        with st.chat_message("assistant"):
            full_res = ""
            box = st.empty()
            
            # System Message: Answer Time/Date ONLY IF ASKED
            sys_msg = (
                f"You are Pro AI. Context: Today is {current_date}, Time is {current_time}. "
                "Respond in English. If the user asks for time, date, or weather, "
                "you MUST provide it accurately. Otherwise, DO NOT mention time or date "
                "in your response."
            )

            completion = client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=[{"role": "system", "content": sys_msg}, {"role": "user", "content": u_query}],
                stream=True
            )

            for chunk in completion:
                if chunk.choices[0].delta.content:
                    full_res += chunk.choices[0].delta.content
                    box.markdown(full_res + "▌")
            
            box.markdown(full_res)
            st.session_state.messages.append({"role": "assistant", "content": full_res})

            # English TTS Generation
            tts = gTTS(text=full_res, lang='en', tld='com.au')
            tts.save("ans.mp3")
            with open("ans.mp3", "rb") as f:
                st.session_state.last_audio_content = f.read()
            st.rerun()

    except Exception as e:
        st.error(f"AI Engine Error: {e}")

# ================= AUDIO RESPONSE PLAYER =================
if st.session_state.last_audio_content:
    if st.button("🔈 Hear listen "):
        st.audio(st.session_state.last_audio_content, format="audio/mp3", autoplay=True)
